spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/my_knowledge_hub
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder:
                log_bind_parameters: true

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security:
          web: error

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: dev.mkhub.knowledge.search.dto

