spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  messages:
    basename: ValidationMessages
    encoding: UTF-8

  datasource:
    url: jdbc:mariadb://localhost:3306/my_knowledge_hub
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder:
                log_bind_parameters: true

server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: dev.mkhub.knowledge.search.dto


logging:
  level:
    root: info
    # MyBatis Mapper 로그
    dev.mkhub.knowledge: DEBUG       # ← 너의 Mapper 패키지명
    org.apache.ibatis: DEBUG                # MyBatis 내부 SQL 로그
    org.mybatis: DEBUG                      # MyBatis 스프링 연동 로그



  messages:
    basename: ValidationMessages
    encoding: UTF-8


file:
  upload:
    path:
      images:
        base-dir : C:/devtools/zmylong/st_proejct/uploads/images/
        public-url: /uploads/images/
      attachments: C:/devtools/zmylong/st_proejct/uploads/attachments/
      profile-image:
        base-dir : C:/devtools/zmylong/st_proejct/uploads/profile_image
        public-url: /uploads/profile_image/

